### PR TITLE
Documentation and things

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
This may be subject to change as it requires some discussion with @ggabernet on how we want to do this.

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
I think we should merge this, there are too many changes in this PR overall. We can discuss the header and logos etc outside of this PR

**Comment by FriederikeHanssen** [comment]
@matrulda added a bit to the docu. Feel free to correct everything I am not explaining well. Also haven't gotten around to the output yet.

**Comment by matrulda** [comment]
Cool cool! Just at first glance: there are a lot of new files. Looks like a lot of result files, I guess they were committed by mistake?

**Comment by FriederikeHanssen** [comment]
oh shoot! Not sure how that happened. Will remove them

**Comment by matrulda** [comment]
Awesome work @FriederikeHanssen ! Looks very good to me. Only have one question, right now the empty bam isn't used as far as I can see. Is the plan to include it in a test later?

**Comment by FriederikeHanssen** [comment]
Yes that would be the plan, to catch empty or corrupted files but run the others through. I haven't figured out how to do this yet and report back to the user. Maybe I can somehow use `errorStrategies` for that

**Comment by matrulda** [comment]
Yeah, maybe the error code for "corrupt/empty bam" can be assigned the `ignore` strategy. I'm unsure how it will play out downstream though. 

But so for this PR, I think it would be more clean to not include that file until is used in a test. But since this is WIP anyway,I'm fine with merging if you'd like to keep it.

**Comment by FriederikeHanssen** [comment]
You are right. Will remove it here and merge, if that is good for you. Probably better to add this as issue so I won't forget it later

**Comment by matrulda** [comment]
Yes, sound good! 👍

**Pull request merged**
