### PR TITLE
Stats & some other minor changes

### PR DESCRIPTION
**Pull request by FriederikeHanssen**
Many thanks to contributing to qbic-pipelines/bamtofastq!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

As discussed on slack, this pipeline can now be run without any stats computation. This should speed up the process. Additionally, some further minor changes were made: updated testate for index files, changed, and docs. 

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, add test data to `testdata/` 
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`). 
 - [x] Documentation in `docs` is updated
 - [x] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/qbic-pipelines/bamtofastq/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by FriederikeHanssen** [comment]
I am afraid the CI tests are not passing. as far as I see the reason is, that the test data is not merged yet, but I have updated the config already.

**Review by ggabernet — APPROVED** [review]
Looks good to me! We also forgot the docs 😄  I'm not used to updating that any more since we have the params schema

**Comment by ggabernet** [comment]
The `bai` for the tests are missing from the test data though

**Comment by FriederikeHanssen** [comment]
I see them here. They will be merged in now, which makes the tests fail right now :( 
Screenshot 2021-04-13 at 18 22 07

**Review by SusiJo — APPROVED** [review]

**Review by SusiJo — APPROVED** [review]
Please double-check the table of contents for the docs/usage and the new command-line flags

The rest looks good to me 👍

**Pull request merged**
